language: node_js

node_js:
  - 7.10.0

before_install:
  - cd styleguide
  - composer install --no-interaction
  - npm i -g npm@5.6.0

install:
  - npm install

script:
  - gulp test

#after_success:
#  - "$TRAVIS_BUILD_DIR/scripts/deploy-gh-pages"

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: $TRAVIS_BUILD_DIR/public
  github-token: $GITHUB_TOKEN
  keep-history: true
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: develop
    tags: true
