language: node_js

node_js:
  - 7.10.0

before_install:
  - cd styleguide
  - composer install --no-interaction
  - npm i -g npm@5.6.0

install:
  - npm install

script:
  - gulp test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
