language: node_js

node_js:
  - 7.10.0

before_install:
  - cd styleguide
  - composer install --no-interaction
  - npm i -g npm@5.6.0

install:
  - npm install

script:
  - gulp test

after_success:
  - "$TRAVIS_BUILD_DIR/scripts/deploy-gh-pages"
