addons:
  chrome: beta
language: node_js
node_js:
  - 7.10.0
before_install:
  - git config --global user.email publish@travis.github
  - git config --global user.name "Travis"
  - cd styleguide
  - composer install --no-interaction
  - npm i -g npm@5.6.0
install:
  - npm install
script:
  - backstop reference
  - gulp serve
  - backstop test
after_failure:
  - gulp test-results
