addons:
  chrome: beta
language: node_js
node_js:
  - 7.10.0
github-token: $GITHUB_TOKEN
before_install:
  - git config --global user.email deploy@travis-ci.org
  - cd styleguide
  - composer install --no-interaction
  - npm i -g npm@5.6.0
install:
  - npm install
script:
  - gulp test
after_failure:
  - "$TRAVIS_BUILD_DIR/scripts/test-results"
